version: '3.8'
services:
  go-api-book-db:
    container_name: go-api-book-db
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - go-api
networks:
  go-api:

#This following command we can connect to db from cmd
#docker exec -it go-api-book-db psql --username=postgres